# Generated by Django 4.1.3 on 2022-12-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corea',
            new_name='Coreasur',
        ),
    ]
